<?php
require_once 'config.php';
$apks = getJsonData(APKS_FILE);
?><!doctype html>
<html data-bs-theme="light" lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><link rel="icon" href="https://i.ibb.co/8LJmm2FH/20260904-033616.png" type="image/png"><title>HEX PROTOCOL - Downloads</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css"><link rel="stylesheet" href="public.css">
    <script>(function(){var t=localStorage.getItem('selectedTheme')||'light';document.documentElement.setAttribute('data-bs-theme',t==='dark'?'dark':'light');})();</script>
</head>
<body>
<nav class="navbar navbar-expand-lg public-navbar"><div class="container"><a class="navbar-brand fw-bold d-flex align-items-center gap-2" href="index.php"><img src="https://i.ibb.co/8LJmm2FH/20260904-033616.png" alt="HEX PROTOCOL"><span>HEX PROTOCOL</span></a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#publicNavbar"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="publicNavbar"><ul class="navbar-nav ms-auto align-items-lg-center"><li class="nav-item"><a class="nav-link" href="index.php">Key Free</a></li><li class="nav-item"><a class="nav-link active" href="downloadapk.php">Downloads</a></li><li class="nav-item"><a class="nav-link" href="login.php">Login</a></li><li class="nav-item"><a class="nav-link" href="register.php">Register</a></li><li class="nav-item"><a class="nav-link" href="#" id="bd-theme" title="Toggle theme"><i class="bi bi-moon-stars" id="bd-theme-icon"></i></a></li></ul></div></div></nav>
<main class="public-main"><div class="container"><div class="page-heading"><div class="public-kicker mb-2">Application downloads</div><h1>Download center</h1><p>Get the latest available application files and release details.</p></div><div class="row g-4"><?php if (empty($apks['apks'])): ?><div class="col-12"><div class="alert alert-info"><i class="bi bi-info-circle me-1"></i>No APK files are available for download yet.</div></div><?php else: foreach ($apks['apks'] as $apk): ?><div class="col-md-6 col-xl-4"><div class="card apk-card"><div class="card-body p-4"><div class="d-flex align-items-start mb-3"><div class="flex-shrink-0 me-3"><?php if (!empty($apk['logo'])): ?><img src="<?php echo htmlspecialchars($apk['logo']); ?>" alt="<?php echo htmlspecialchars($apk['name']); ?>" class="apk-icon-lg"><?php else: ?><div class="apk-icon-lg bg-primary d-flex align-items-center justify-content-center text-white"><i class="bi bi-box-seam fs-3"></i></div><?php endif; ?></div><div class="flex-grow-1"><h2 class="h5 mb-1"><?php echo htmlspecialchars($apk['name']); ?></h2><div class="text-muted small"><i class="bi bi-tag me-1"></i>Version <?php echo htmlspecialchars($apk['version']); ?></div><div class="text-muted small"><i class="bi bi-box me-1"></i><?php echo htmlspecialchars($apk['package']); ?></div></div></div><?php if (!empty($apk['description'])): ?><p class="text-muted small mb-3"><?php echo htmlspecialchars($apk['description']); ?></p><?php endif; ?><div class="d-flex gap-2"><span class="badge text-bg-info"><i class="bi bi-hdd me-1"></i><?php echo htmlspecialchars($apk['size'] ?? '—'); ?></span><span class="badge text-bg-success"><i class="bi bi-download me-1"></i><?php echo htmlspecialchars($apk['downloads'] ?? 0); ?></span></div></div><div class="card-footer p-3"><a href="<?php echo htmlspecialchars($apk['file_url']); ?>" class="btn btn-primary w-100" target="_blank" rel="noopener"><i class="bi bi-download me-1"></i>Download APK</a></div></div></div><?php endforeach; endif; ?></div></div></main>
<footer class="public-footer py-3"><div class="container d-flex justify-content-between align-items-center"><small>&copy; 2018 - 2026 HEX PROTOCOL</small><a href="index.php" class="small"><i class="bi bi-arrow-left me-1"></i>Back to key generator</a></div></footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script src="public.js"></script>
</body></html>
