<?php require_once 'config.php'; ?><!doctype html>
<html data-bs-theme="light" lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark">
    <link rel="icon" href="https://i.ibb.co/8LJmm2FH/20260904-033616.png" type="image/png"><title>HEX PROTOCOL - Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css"><link rel="stylesheet" href="public.css">
    <script>(function(){var t=localStorage.getItem('selectedTheme')||'light';document.documentElement.setAttribute('data-bs-theme',t==='dark'?'dark':'light');})();</script>
</head>
<body class="auth-page">
<nav class="navbar navbar-expand-lg public-navbar fixed-top"><div class="container"><a class="navbar-brand fw-bold d-flex align-items-center gap-2" href="index.php"><img src="https://i.ibb.co/8LJmm2FH/20260904-033616.png" alt="HEX PROTOCOL"><span>HEX PROTOCOL</span></a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#publicNavbar"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="publicNavbar"><ul class="navbar-nav ms-auto align-items-lg-center"><li class="nav-item"><a class="nav-link" href="index.php">Key Free</a></li><li class="nav-item"><a class="nav-link" href="downloadapk.php">Downloads</a></li><li class="nav-item"><a class="nav-link active" href="login.php">Login</a></li><li class="nav-item"><a class="nav-link" href="register.php">Register</a></li><li class="nav-item"><a class="nav-link" href="#" id="bd-theme" title="Toggle theme"><i class="bi bi-moon-stars" id="bd-theme-icon"></i></a></li></ul></div></div></nav>
<main class="auth-wrap"><div class="auth-box"><div class="auth-brand"><img src="https://i.ibb.co/8LJmm2FH/20260904-033616.png" alt="HEX PROTOCOL"><h1>Welcome back</h1><p>Sign in to start your session.</p></div><div class="card card-primary card-outline auth-card"><div class="card-body"><form action="index.php" method="post"><div class="mb-3"><label class="form-label" for="username">Username</label><div class="input-group"><input type="text" class="form-control" name="username" id="username" placeholder="Username" required minlength="4"><span class="input-group-text"><i class="bi bi-person"></i></span></div></div><div class="mb-3"><label class="form-label" for="password">Password</label><div class="input-group"><input type="password" class="form-control" name="password" id="password" placeholder="Password" required minlength="6"><span class="input-group-text"><i class="bi bi-lock-fill"></i></span></div></div><div class="d-flex align-items-center justify-content-between gap-3 mb-3"><div class="form-check"><input type="checkbox" class="form-check-input" name="stay_log" id="stay_log" value="yes"><label class="form-check-label small" for="stay_log">Remember me</label></div><button type="submit" class="btn btn-primary px-3"><i class="bi bi-box-arrow-in-right me-1"></i>Sign In</button></div></form><hr><p class="text-center small mb-2"><a href="register.php">Register a new account</a></p><div class="auth-note text-center">Need a reseller account? Contact Admin:<br><a href="https://t.me/Noveryy" target="_blank" rel="noopener" class="text-decoration-none fw-semibold"><i class="bi bi-telegram text-info me-1"></i>t.me/Noveryy</a></div></div></div></div></main>
<footer class="public-footer py-3"><div class="container d-flex justify-content-between align-items-center"><small>&copy; 2018 - 2026 HEX PROTOCOL</small><a href="index.php" class="small"><i class="bi bi-arrow-left me-1"></i>Back to key generator</a></div></footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script src="public.js"></script>
</body></html>
