<?php
require_once 'config.php';
$settings = settings();
$referralCode = $settings['referral_code'] ?? 'HEX2024';
?><!doctype html>
<html data-bs-theme="light" lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark">
    <link rel="icon" href="https://i.ibb.co/8LJmm2FH/20260904-033616.png" type="image/png"><title>HEX PROTOCOL - Register</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css"><link rel="stylesheet" href="public.css">
    <script>(function(){var t=localStorage.getItem('selectedTheme')||'light';document.documentElement.setAttribute('data-bs-theme',t==='dark'?'dark':'light');})();</script>
</head>
<body class="auth-page">
<nav class="navbar navbar-expand-lg public-navbar fixed-top"><div class="container"><a class="navbar-brand fw-bold d-flex align-items-center gap-2" href="index.php"><img src="https://i.ibb.co/8LJmm2FH/20260904-033616.png" alt="HEX PROTOCOL"><span>HEX PROTOCOL</span></a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#publicNavbar"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="publicNavbar"><ul class="navbar-nav ms-auto align-items-lg-center"><li class="nav-item"><a class="nav-link" href="index.php">Key Free</a></li><li class="nav-item"><a class="nav-link" href="downloadapk.php">Downloads</a></li><li class="nav-item"><a class="nav-link" href="login.php">Login</a></li><li class="nav-item"><a class="nav-link active" href="register.php">Register</a></li><li class="nav-item"><a class="nav-link" href="#" id="bd-theme" title="Toggle theme"><i class="bi bi-moon-stars" id="bd-theme-icon"></i></a></li></ul></div></div></nav>
<main class="auth-wrap"><div class="auth-box"><div class="auth-brand"><img src="https://i.ibb.co/8LJmm2FH/20260904-033616.png" alt="HEX PROTOCOL"><h1>Create an account</h1><p>Register to access your reseller session.</p></div><div class="card card-primary card-outline auth-card"><div class="card-body"><form action="index.php" method="post"><div class="mb-3"><label class="form-label" for="username">Username</label><div class="input-group"><input type="text" class="form-control" name="username" id="username" placeholder="Username" minlength="4" maxlength="24" required><span class="input-group-text"><i class="bi bi-person"></i></span></div></div><div class="mb-3"><label class="form-label" for="password">Password</label><div class="input-group"><input type="password" class="form-control" name="password" id="password" placeholder="Password" minlength="6" maxlength="24" required><span class="input-group-text"><i class="bi bi-lock-fill"></i></span></div></div><div class="mb-3"><label class="form-label" for="password2">Retype password</label><div class="input-group"><input type="password" name="password2" id="password2" class="form-control" placeholder="Retype password" minlength="6" maxlength="24" required><span class="input-group-text"><i class="bi bi-lock-fill"></i></span></div></div><div class="mb-3"><label class="form-label" for="referral">Referral code</label><div class="input-group"><input type="text" name="referral" id="referral" class="form-control" placeholder="Referral code" value="<?php echo htmlspecialchars($referralCode); ?>" maxlength="25" required><span class="input-group-text"><i class="bi bi-upc-scan"></i></span></div></div><button type="submit" class="btn btn-primary w-100"><i class="bi bi-person-plus me-1"></i>Register</button></form><hr><p class="text-center small mb-0"><a href="login.php">I already have an account</a></p></div></div></div></main>
<footer class="public-footer py-3"><div class="container d-flex justify-content-between align-items-center"><small>&copy; 2018 - 2026 HEX PROTOCOL</small><a href="index.php" class="small"><i class="bi bi-arrow-left me-1"></i>Back to key generator</a></div></footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script src="public.js"></script>
</body></html>
